In [2]:
from bs4 import BeautifulSoup
import requests

## 1.Write a python program to display all the header tags from wikipedia.org.

In [3]:
page=requests.get("https://en.wikipedia.org/wiki/Main_Page")

In [4]:
page

In [6]:
soup=BeautifulSoup(page.content)
heading=soup.find('h2',class_="mp-h2")

In [7]:
heading

In [8]:
heading.text

"From today's featured article"

In [9]:
headings=[]
for i in soup.find_all('h2',class_="mp-h2"):
    headings.append(i.text)
    
headings

["From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "From today's featured list",
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

In [11]:
headings1=[]
for i in soup.find_all('h1',class_="firstHeading"):
    headings1.append(i.text)
    
headings1

['Main Page']

## 2. Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. name, rating, year of release) and make data frame.

In [22]:
page1=requests.get("https://www.imdb.com/chart/top/?ref_=nv_mv_250")

In [23]:
page1

In [24]:
soup_imdb=BeautifulSoup(page1.content)

In [26]:
name=[]
for i in soup_imdb.find_all('td',class_="titleColumn"):
    name.append(i.text)
    
name

['\n      1.\n      The Shawshank Redemption\n(1994)\n',
 '\n      2.\n      The Godfather\n(1972)\n',
 '\n      3.\n      The Godfather: Part II\n(1974)\n',
 '\n      4.\n      The Dark Knight\n(2008)\n',
 '\n      5.\n      12 Angry Men\n(1957)\n',
 "\n      6.\n      Schindler's List\n(1993)\n",
 '\n      7.\n      The Lord of the Rings: The Return of the King\n(2003)\n',
 '\n      8.\n      Pulp Fiction\n(1994)\n',
 '\n      9.\n      Il buono, il brutto, il cattivo\n(1966)\n',
 '\n      10.\n      The Lord of the Rings: The Fellowship of the Ring\n(2001)\n',
 '\n      11.\n      Fight Club\n(1999)\n',
 '\n      12.\n      Forrest Gump\n(1994)\n',
 '\n      13.\n      Inception\n(2010)\n',
 '\n      14.\n      The Lord of the Rings: The Two Towers\n(2002)\n',
 '\n      15.\n      Star Wars: Episode V - The Empire Strikes Back\n(1980)\n',
 '\n      16.\n      The Matrix\n(1999)\n',
 '\n      17.\n      Goodfellas\n(1990)\n',
 "\n      18.\n      One Flew Over the Cuckoo's Nest\n(1975)\n",
 '\n      19.\n      Shichinin no samurai\n(1954)\n',
 '\n      20.\n      Se7en\n(1995)\n',
 '\n      21.\n      The Silence of the Lambs\n(1991)\n',
 '\n      22.\n      Cidade de Deus\n(2002)\n',
 '\n      23.\n      La vita è bella\n(1997)\n',
 "\n      24.\n      It's a Wonderful Life\n(1946)\n",
 '\n      25.\n      Star Wars\n(1977)\n',
 '\n      26.\n      Saving Private Ryan\n(1998)\n',
 '\n      27.\n      Interstellar\n(2014)\n',
 '\n      28.\n      Sen to Chihiro no kamikakushi\n(2001)\n',
 '\n      29.\n      The Green Mile\n(1999)\n',
 '\n      30.\n      Gisaengchung\n(2019)\n',
 '\n      31.\n      Léon\n(1994)\n',
 '\n      32.\n      Seppuku\n(1962)\n',
 '\n      33.\n      The Pianist\n(2002)\n',
 '\n      34.\n      Terminator 2: Judgment Day\n(1991)\n',
 '\n      35.\n      The Usual Suspects\n(1995)\n',
 '\n      36.\n      Back to the Future\n(1985)\n',
 '\n      37.\n      Psycho\n(1960)\n',
 '\n      38.\n      The Lion King\n(1994)\n',
 '\n      39.\n      Modern Times\n(1936)\n',
 '\n      40.\n      American History X\n(1998)\n',
 '\n      41.\n      Hotaru no haka\n(1988)\n',
 '\n      42.\n      City Lights\n(1931)\n',
 '\n      43.\n      Whiplash\n(2014)\n',
 '\n      44.\n      Gladiator\n(2000)\n',
 '\n      45.\n      The Departed\n(2006)\n',
 '\n      46.\n      The Intouchables\n(2011)\n',
 '\n      47.\n      The Prestige\n(2006)\n',
 '\n      48.\n      Casablanca\n(1942)\n',
 '\n      49.\n      Once Upon a Time in the West\n(1968)\n',
 '\n      50.\n      Rear Window\n(1954)\n',
 '\n      51.\n      Nuovo Cinema Paradiso\n(1988)\n',
 '\n      52.\n      Alien\n(1979)\n',
 '\n      53.\n      Apocalypse Now\n(1979)\n',
 '\n      54.\n      Memento\n(2000)\n',
 '\n      55.\n      Raiders of the Lost Ark\n(1981)\n',
 '\n      56.\n      The Great Dictator\n(1940)\n',
 '\n      57.\n      The Lives of Others\n(2006)\n',
 '\n      58.\n      Django Unchained\n(2012)\n',
 '\n      59.\n      Paths of Glory\n(1957)\n',
 '\n      60.\n      Sunset Blvd.\n(1950)\n',
 '\n      61.\n      WALL·E\n(2008)\n',
 '\n      62.\n      Avengers: Infinity War\n(2018)\n',
 '\n      63.\n      Witness for the Prosecution\n(1957)\n',
 '\n      64.\n      The Shining\n(1980)\n',
 '\n      65.\n      Spider-Man: Into the Spider-Verse\n(2018)\n',
 '\n      66.\n      Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb\n(1964)\n',
 '\n      67.\n      Mononoke-hime\n(1997)\n',
 '\n      68.\n      Joker\n(2019)\n',
 '\n      69.\n      Oldeuboi\n(2003)\n',
 '\n      70.\n      Kimi no na wa.\n(2016)\n',
 '\n      71.\n      Coco\n(2017)\n',
 '\n      72.\n      The Dark Knight Rises\n(2012)\n',
 '\n      73.\n      Aliens\n(1986)\n',
 '\n      74.\n      Once Upon a Time in America\n(1984)\n',
 '\n      75.\n      Avengers: Endgame\n(2019)\n',
 '\n      76.\n      Capharnaüm\n(2018)\n',
 '\n      77.\n      Das Boot\n(1981)\n',
 '\n      78.\n      Tengoku to jigoku\n(1963)\n',
 '\n      79.\n      American Beauty\n(1999)\n',
 '\n      80.\n      3 Idiots\n(2009)\n',
 '\n      81.\n      Toy Story\n(1995)\n',
 '\n      82.\n      Amadeus\n(1984)\n',
 '\n      83.\n      Braveheart\n(1995)\n',
 '\n      84.\n      Hamilton\n(2020)\n',
 '\n      85.\n      Inglourious Basterds\n(2009)\n',
 '\n      86.\n      Good Will Hunting\n(1997)\n',
 '\n      87.\n      Star Wars: Episode VI - Return of the Jedi\n(1983)\n',
 '\n      88.\n      2001: A Space Odyssey\n(1968)\n',
 '\n      89.\n      Reservoir Dogs\n(1992)\n',
 '\n      90.\n      M - Eine Stadt sucht einen Mörder\n(1931)\n',
 '\n      91.\n      Vertigo\n(1958)\n',
 '\n      92.\n      Taare Zameen Par\n(2007)\n',
 '\n      93.\n      Idi i smotri\n(1985)\n',
 '\n      94.\n      Citizen Kane\n(1941)\n',
 '\n      95.\n      Jagten\n(2012)\n',
 '\n      96.\n      Requiem for a Dream\n(2000)\n',
 "\n      97.\n      Singin' in the Rain\n(1952)\n",
 '\n      98.\n      North by Northwest\n(1959)\n',
 '\n      99.\n      Eternal Sunshine of the Spotless Mind\n(2004)\n',
 '\n      100.\n      Ladri di biciclette\n(1948)\n',
 '\n      101.\n      Ikiru\n(1952)\n',
 '\n      102.\n      Lawrence of Arabia\n(1962)\n',
 '\n      103.\n      The Kid\n(1921)\n',
 '\n      104.\n      Jai Bhim\n(2021)\n',
 '\n      105.\n      Full Metal Jacket\n(1987)\n',
 '\n      106.\n      Dangal\n(2016)\n',
 '\n      107.\n      The Apartment\n(1960)\n',
 '\n      108.\n      The Father\n(2020)\n',
 '\n      109.\n      Incendies\n(2010)\n',
 '\n      110.\n      Metropolis\n(1927)\n',
 '\n      111.\n      A Clockwork Orange\n(1971)\n',
 '\n      112.\n      Double Indemnity\n(1944)\n',
 '\n      113.\n      Taxi Driver\n(1976)\n',
 '\n      114.\n      Pather Panchali\n(1955)\n',
 '\n      115.\n      Jodaeiye Nader az Simin\n(2011)\n',
 '\n      116.\n      The Sting\n(1973)\n',
 '\n      117.\n      Scarface\n(1983)\n',
 '\n      118.\n      Snatch\n(2000)\n',
 '\n      119.\n      1917\n(2019)\n',
 "\n      120.\n      Le fabuleux destin d'Amélie Poulain\n(2001)\n",
 '\n      121.\n      To Kill a Mockingbird\n(1962)\n',
 '\n      122.\n      Toy Story 3\n(2010)\n',
 '\n      123.\n      Per qualche dollaro in più\n(1965)\n',
 '\n      124.\n      Up\n(2009)\n',
 '\n      125.\n      Indiana Jones and the Last Crusade\n(1989)\n',
 '\n      126.\n      Heat\n(1995)\n',
 '\n      127.\n      L.A. Confidential\n(1997)\n',
 '\n      128.\n      Yôjinbô\n(1961)\n',
 '\n      129.\n      Ran\n(1985)\n',
 '\n      130.\n      Die Hard\n(1988)\n',
 '\n      131.\n      Rashômon\n(1950)\n',
 '\n      132.\n      Green Book\n(2018)\n',
 '\n      133.\n      Der Untergang\n(2004)\n',
 '\n      134.\n      Monty Python and the Holy Grail\n(1975)\n',
 '\n      135.\n      All About Eve\n(1950)\n',
 '\n      136.\n      Some Like It Hot\n(1959)\n',
 '\n      137.\n      Batman Begins\n(2005)\n',
 '\n      138.\n      Unforgiven\n(1992)\n',
 '\n      139.\n      Bacheha-Ye aseman\n(1997)\n',
 '\n      140.\n      Hauru no ugoku shiro\n(2004)\n',
 '\n      141.\n      The Wolf of Wall Street\n(2013)\n',
 '\n      142.\n      Judgment at Nuremberg\n(1961)\n',
 '\n      143.\n      The Great Escape\n(1963)\n',
 '\n      144.\n      Casino\n(1995)\n',
 '\n      145.\n      There Will Be Blood\n(2007)\n',
 '\n      146.\n      The Treasure of the Sierra Madre\n(1948)\n',
 "\n      147.\n      Pan's Labyrinth\n(2006)\n",
 '\n      148.\n      A Beautiful Mind\n(2001)\n',
 '\n      149.\n      El secreto de sus ojos\n(2009)\n',
 '\n      150.\n      Dersu Uzala\n(1975)\n',
 '\n      151.\n      Raging Bull\n(1980)\n',
 '\n      152.\n      Chinatown\n(1974)\n',
 '\n      153.\n      Tonari no Totoro\n(1988)\n',
 '\n      154.\n      Dune: Part One\n(2021)\n',
 '\n      155.\n      Lock, Stock and Two Smoking Barrels\n(1998)\n',
 '\n      156.\n      Shutter Island\n(2010)\n',
 '\n      157.\n      The Gold Rush\n(1925)\n',
 '\n      158.\n      No Country for Old Men\n(2007)\n',
 '\n      159.\n      Dial M for Murder\n(1954)\n',
 '\n      160.\n      Det sjunde inseglet\n(1957)\n',
 '\n      161.\n      Three Billboards Outside Ebbing, Missouri\n(2017)\n',
 '\n      162.\n      The Thing\n(1982)\n',
 '\n      163.\n      The Elephant Man\n(1980)\n',
 '\n      164.\n      The Sixth Sense\n(1999)\n',
 '\n      165.\n      Klaus\n(2019)\n',
 '\n      166.\n      Smultronstället\n(1957)\n',
 '\n      167.\n      The Third Man\n(1949)\n',
 '\n      168.\n      Jurassic Park\n(1993)\n',
 '\n      169.\n      The Truman Show\n(1998)\n',
 '\n      170.\n      V for Vendetta\n(2005)\n',
 '\n      171.\n      Salinui chueok\n(2003)\n',
 '\n      172.\n      Blade Runner\n(1982)\n',
 '\n      173.\n      Inside Out\n(2015)\n',
 '\n      174.\n      Trainspotting\n(1996)\n',
 '\n      175.\n      The Bridge on the River Kwai\n(1957)\n',
 '\n      176.\n      Fargo\n(1996)\n',
 '\n      177.\n      Warrior\n(2011)\n',
 '\n      178.\n      Finding Nemo\n(2003)\n',
 '\n      179.\n      Kill Bill: Vol. 1\n(2003)\n',
 '\n      180.\n      Gone with the Wind\n(1939)\n',
 '\n      181.\n      Tôkyô monogatari\n(1953)\n',
 '\n      182.\n      On the Waterfront\n(1954)\n',
 '\n      183.\n      Babam ve Oglum\n(2005)\n',
 '\n      184.\n      Stalker\n(1979)\n',
 '\n      185.\n      Relatos salvajes\n(2014)\n',
 '\n      186.\n      Z\n(1969)\n',
 '\n      187.\n      The Deer Hunter\n(1978)\n',
 '\n      188.\n      Prisoners\n(2013)\n',
 '\n      189.\n      Gran Torino\n(2008)\n',
 '\n      190.\n      The General\n(1926)\n',
 '\n      191.\n      The Grand Budapest Hotel\n(2014)\n',
 '\n      192.\n      Persona\n(1966)\n',
 '\n      193.\n      Sherlock Jr.\n(1924)\n',
 '\n      194.\n      Before Sunrise\n(1995)\n',
 '\n      195.\n      Mary and Max.\n(2009)\n',
 '\n      196.\n      96\n(2018)\n',
 '\n      197.\n      Mr. Smith Goes to Washington\n(1939)\n',
 '\n      198.\n      Catch Me If You Can\n(2002)\n',
 '\n      199.\n      In the Name of the Father\n(1993)\n',
 '\n      200.\n      Room\n(2015)\n',
 '\n      201.\n      Barry Lyndon\n(1975)\n',
 '\n      202.\n      Gone Girl\n(2014)\n',
 '\n      203.\n      Hacksaw Ridge\n(2016)\n',
 "\n      204.\n      La passion de Jeanne d'Arc\n(1928)\n",
 '\n      205.\n      Andhadhun\n(2018)\n',
 '\n      206.\n      Ford v Ferrari\n(2019)\n',
 '\n      207.\n      12 Years a Slave\n(2013)\n',
 '\n      208.\n      To Be or Not to Be\n(1942)\n',
 '\n      209.\n      The Big Lebowski\n(1998)\n',
 '\n      210.\n      Höstsonaten\n(1978)\n',
 '\n      211.\n      How to Train Your Dragon\n(2010)\n',
 '\n      212.\n      Dead Poets Society\n(1989)\n',
 '\n      213.\n      Mad Max: Fury Road\n(2015)\n',
 '\n      214.\n      Ben-Hur\n(1959)\n',
 '\n      215.\n      Harry Potter and the Deathly Hallows: Part 2\n(2011)\n',
 '\n      216.\n      Million Dollar Baby\n(2004)\n',
 '\n      217.\n      Le salaire de la peur\n(1953)\n',
 '\n      218.\n      Ah-ga-ssi\n(2016)\n',
 '\n      219.\n      Stand by Me\n(1986)\n',
 '\n      220.\n      Network\n(1976)\n',
 '\n      221.\n      Logan\n(2017)\n',
 '\n      222.\n      Cool Hand Luke\n(1967)\n',
 "\n      223.\n      Hachi: A Dog's Tale\n(2009)\n",
 '\n      224.\n      Gangs of Wasseypur\n(2012)\n',
 '\n      225.\n      La haine\n(1995)\n',
 '\n      226.\n      Les quatre cents coups\n(1959)\n',
 '\n      227.\n      Platoon\n(1986)\n',
 '\n      228.\n      Koe no katachi\n(2016)\n',
 '\n      229.\n      Spotlight\n(2015)\n',
 '\n      230.\n      Monsters, Inc.\n(2001)\n',
 '\n      231.\n      Rebecca\n(1940)\n',
 '\n      232.\n      Life of Brian\n(1979)\n',
 '\n      233.\n      Hotel Rwanda\n(2004)\n',
 '\n      234.\n      Eskiya\n(1996)\n',
 '\n      235.\n      Fa Yeung Nin Wah\n(2000)\n',
 '\n      236.\n      Rush\n(2013)\n',
 '\n      237.\n      Into the Wild\n(2007)\n',
 '\n      238.\n      Amores perros\n(2000)\n',
 '\n      239.\n      Rocky\n(1976)\n',
 '\n      240.\n      Kaze no tani no Naushika\n(1984)\n',
 '\n      241.\n      It Happened One Night\n(1934)\n',
 '\n      242.\n      Andrei Rublev\n(1966)\n',
 '\n      243.\n      Before Sunset\n(2004)\n',
 '\n      244.\n      Fanny och Alexander\n(1982)\n',
 '\n      245.\n      La battaglia di Algeri\n(1966)\n',
 '\n      246.\n      Shin seiki Evangelion Gekijô-ban: Air/Magokoro wo, kimi ni\n(1997)\n',
 '\n      247.\n      Le notti di Cabiria\n(1957)\n',
 '\n      248.\n      The Princess Bride\n(1987)\n',
 '\n      249.\n      Paris, Texas\n(1984)\n',
 '\n      250.\n      Trois couleurs: Rouge\n(1994)\n']

In [32]:
rating=[]
for i in soup_imdb.find_all('td',class_="ratingColumn imdbRating"):
    rating.append(i.text)
    
rating

['\n9.2\n',
 '\n9.1\n',
 '\n9.0\n',
 '\n9.0\n',
 '\n8.9\n',
 '\n8.9\n',
 '\n8.9\n',
 '\n8.8\n',
 '\n8.8\n',
 '\n8.8\n',
 '\n8.8\n',
 '\n8.7\n',
 '\n8.7\n',
 '\n8.7\n',
 '\n8.7\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.6\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n']

In [28]:
release_year=[]
for i in soup_imdb.find_all('span',class_="secondaryInfo"):
    release_year.append(i.text)
    
release_year

['(1994)',
 '(1972)',
 '(1974)',
 '(2008)',
 '(1957)',
 '(1993)',
 '(2003)',
 '(1994)',
 '(1966)',
 '(2001)',
 '(1999)',
 '(1994)',
 '(2010)',
 '(2002)',
 '(1980)',
 '(1999)',
 '(1990)',
 '(1975)',
 '(1954)',
 '(1995)',
 '(1991)',
 '(2002)',
 '(1997)',
 '(1946)',
 '(1977)',
 '(1998)',
 '(2014)',
 '(2001)',
 '(1999)',
 '(2019)',
 '(1994)',
 '(1962)',
 '(2002)',
 '(1991)',
 '(1995)',
 '(1985)',
 '(1960)',
 '(1994)',
 '(1936)',
 '(1998)',
 '(1988)',
 '(1931)',
 '(2014)',
 '(2000)',
 '(2006)',
 '(2011)',
 '(2006)',
 '(1942)',
 '(1968)',
 '(1954)',
 '(1988)',
 '(1979)',
 '(1979)',
 '(2000)',
 '(1981)',
 '(1940)',
 '(2006)',
 '(2012)',
 '(1957)',
 '(1950)',
 '(2008)',
 '(2018)',
 '(1957)',
 '(1980)',
 '(2018)',
 '(1964)',
 '(1997)',
 '(2019)',
 '(2003)',
 '(2016)',
 '(2017)',
 '(2012)',
 '(1986)',
 '(1984)',
 '(2019)',
 '(2018)',
 '(1981)',
 '(1963)',
 '(1999)',
 '(2009)',
 '(1995)',
 '(1984)',
 '(1995)',
 '(2020)',
 '(2009)',
 '(1997)',
 '(1983)',
 '(1968)',
 '(1992)',
 '(1931)',
 '(1958)',
 '(2007)',
 '(1985)',
 '(1941)',
 '(2012)',
 '(2000)',
 '(1952)',
 '(1959)',
 '(2004)',
 '(1948)',
 '(1952)',
 '(1962)',
 '(1921)',
 '(2021)',
 '(1987)',
 '(2016)',
 '(1960)',
 '(2020)',
 '(2010)',
 '(1927)',
 '(1971)',
 '(1944)',
 '(1976)',
 '(1955)',
 '(2011)',
 '(1973)',
 '(1983)',
 '(2000)',
 '(2019)',
 '(2001)',
 '(1962)',
 '(2010)',
 '(1965)',
 '(2009)',
 '(1989)',
 '(1995)',
 '(1997)',
 '(1961)',
 '(1985)',
 '(1988)',
 '(1950)',
 '(2018)',
 '(2004)',
 '(1975)',
 '(1950)',
 '(1959)',
 '(2005)',
 '(1992)',
 '(1997)',
 '(2004)',
 '(2013)',
 '(1961)',
 '(1963)',
 '(1995)',
 '(2007)',
 '(1948)',
 '(2006)',
 '(2001)',
 '(2009)',
 '(1975)',
 '(1980)',
 '(1974)',
 '(1988)',
 '(2021)',
 '(1998)',
 '(2010)',
 '(1925)',
 '(2007)',
 '(1954)',
 '(1957)',
 '(2017)',
 '(1982)',
 '(1980)',
 '(1999)',
 '(2019)',
 '(1957)',
 '(1949)',
 '(1993)',
 '(1998)',
 '(2005)',
 '(2003)',
 '(1982)',
 '(2015)',
 '(1996)',
 '(1957)',
 '(1996)',
 '(2011)',
 '(2003)',
 '(2003)',
 '(1939)',
 '(1953)',
 '(1954)',
 '(2005)',
 '(1979)',
 '(2014)',
 '(1969)',
 '(1978)',
 '(2013)',
 '(2008)',
 '(1926)',
 '(2014)',
 '(1966)',
 '(1924)',
 '(1995)',
 '(2009)',
 '(2018)',
 '(1939)',
 '(2002)',
 '(1993)',
 '(2015)',
 '(1975)',
 '(2014)',
 '(2016)',
 '(1928)',
 '(2018)',
 '(2019)',
 '(2013)',
 '(1942)',
 '(1998)',
 '(1978)',
 '(2010)',
 '(1989)',
 '(2015)',
 '(1959)',
 '(2011)',
 '(2004)',
 '(1953)',
 '(2016)',
 '(1986)',
 '(1976)',
 '(2017)',
 '(1967)',
 '(2009)',
 '(2012)',
 '(1995)',
 '(1959)',
 '(1986)',
 '(2016)',
 '(2015)',
 '(2001)',
 '(1940)',
 '(1979)',
 '(2004)',
 '(1996)',
 '(2000)',
 '(2013)',
 '(2007)',
 '(2000)',
 '(1976)',
 '(1984)',
 '(1934)',
 '(1966)',
 '(2004)',
 '(1982)',
 '(1966)',
 '(1997)',
 '(1957)',
 '(1987)',
 '(1984)',
 '(1994)']

In [30]:
# Making dataframe 
import pandas as pd
df1=pd.DataFrame({'Movie_Name':name,'Released_year':release_year,'Rating':rating})
df2=df1.iloc[:100]
df2

                                           Movie_Name Released_year   Rating
0   \n      1.\n      The Shawshank Redemption\n(1...        (1994)  \n9.2\n
1           \n      2.\n      The Godfather\n(1972)\n        (1972)  \n9.1\n
2   \n      3.\n      The Godfather: Part II\n(197...        (1974)  \n9.0\n
3         \n      4.\n      The Dark Knight\n(2008)\n        (2008)  \n9.0\n
4            \n      5.\n      12 Angry Men\n(1957)\n        (1957)  \n8.9\n
..                                                ...           ...      ...
95   \n      96.\n      Requiem for a Dream\n(2000)\n        (2000)  \n8.3\n
96   \n      97.\n      Singin' in the Rain\n(1952)\n        (1952)  \n8.3\n
97    \n      98.\n      North by Northwest\n(1959)\n        (1959)  \n8.3\n
98  \n      99.\n      Eternal Sunshine of the Spo...        (2004)  \n8.3\n
99  \n      100.\n      Ladri di biciclette\n(1948)\n        (1948)  \n8.3\n

[100 rows x 3 columns]

## 3. Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. name, rating, year of release) and make data frame.

In [33]:
page2=requests.get("https://www.imdb.com/india/top-rated-indian-movies/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=461131e5-5af0-4e50-bee2-223fad1e00ca&pf_rd_r=K3SG3D3WHC2C86YHBCTF&pf_rd_s=center-1&pf_rd_t=60601&pf_rd_i=india.toprated&ref_=fea_india_ss_toprated_india_tr_india250_hd")

In [34]:
page2

In [35]:
soup_india=BeautifulSoup(page2.content)

In [36]:
name_india=[]
for i in soup_india.find_all('td',class_="titleColumn"):
    name_india.append(i.text)
    
name_india

['\n      1.\n      Jai Bhim\n(2021)\n',
 '\n      2.\n      Nayakan\n(1987)\n',
 '\n      3.\n      Pariyerum Perumal\n(2018)\n',
 '\n      4.\n      Anbe Sivam\n(2003)\n',
 '\n      5.\n      Sardar Udham\n(2021)\n',
 '\n      6.\n      C/o Kancharapalem\n(2018)\n',
 '\n      7.\n      Kireedam\n(1989)\n',
 '\n      8.\n      Manichitrathazhu\n(1993)\n',
 '\n      9.\n      Golmaal\n(1979)\n',
 '\n      10.\n      Apur Sansar\n(1959)\n',
 '\n      11.\n      Natsamrat\n(2016)\n',
 '\n      12.\n      Thevar Magan\n(1992)\n',
 '\n      13.\n      96\n(2018)\n',
 '\n      14.\n      Kumbalangi Nights\n(2019)\n',
 '\n      15.\n      Black Friday\n(2004)\n',
 '\n      16.\n      Pather Panchali\n(1955)\n',
 '\n      17.\n      #Home\n(2021)\n',
 '\n      18.\n      Soorarai Pottru\n(2020)\n',
 '\n      19.\n      Visaaranai\n(2015)\n',
 '\n      20.\n      Jersey\n(2019)\n',
 '\n      21.\n      3 Idiots\n(2009)\n',
 '\n      22.\n      Asuran\n(2019)\n',
 '\n      23.\n      Taare Zameen Par\n(2007)\n',
 '\n      24.\n      Kaithi\n(2019)\n',
 '\n      25.\n      Sarpatta Parambarai\n(2021)\n',
 '\n      26.\n      Thalapathi\n(1991)\n',
 '\n      27.\n      Drishyam 2\n(2021)\n',
 '\n      28.\n      Devasuram\n(1993)\n',
 '\n      29.\n      Dangal\n(2016)\n',
 '\n      30.\n      Peranbu\n(2018)\n',
 '\n      31.\n      Vada Chennai\n(2018)\n',
 '\n      32.\n      Chithram\n(1988)\n',
 '\n      33.\n      Aparajito\n(1956)\n',
 '\n      34.\n      Jaane Bhi Do Yaaro\n(1983)\n',
 '\n      35.\n      Pyaasa\n(1957)\n',
 '\n      36.\n      Thani Oruvan\n(2015)\n',
 '\n      37.\n      Guide\n(1965)\n',
 '\n      38.\n      Ratsasan\n(2018)\n',
 '\n      39.\n      Spadikam\n(1995)\n',
 '\n      40.\n      Iruvar\n(1997)\n',
 '\n      41.\n      Kannathil Muthamittal\n(2002)\n',
 '\n      42.\n      Agent Sai Srinivasa Athreya\n(2019)\n',
 '\n      43.\n      Chupke Chupke\n(1975)\n',
 '\n      44.\n      Super Deluxe\n(2019)\n',
 '\n      45.\n      Mahanati\n(2018)\n',
 '\n      46.\n      Aruvi\n(2016)\n',
 '\n      47.\n      Pudhu Pettai\n(2006)\n',
 '\n      48.\n      Khosla Ka Ghosla!\n(2006)\n',
 '\n      49.\n      Drishyam\n(2013)\n',
 '\n      50.\n      Anniyan\n(2005)\n',
 '\n      51.\n      Tumbbad\n(2018)\n',
 '\n      52.\n      Premam\n(2015)\n',
 '\n      53.\n      Kaakkaa Muttai\n(2014)\n',
 '\n      54.\n      Mudhalvan\n(1999)\n',
 '\n      55.\n      Vikram Vedha\n(2017)\n',
 '\n      56.\n      Bangalore Days\n(2014)\n',
 '\n      57.\n      Papanasam\n(2015)\n',
 '\n      58.\n      Satya\n(1998)\n',
 '\n      59.\n      Angoor\n(1982)\n',
 '\n      60.\n      Soodhu Kavvum\n(2013)\n',
 '\n      61.\n      Dhuruvangal Pathinaaru\n(2016)\n',
 '\n      62.\n      Mandela\n(2021)\n',
 '\n      63.\n      Andhadhun\n(2018)\n',
 '\n      64.\n      Pithamagan\n(2003)\n',
 '\n      65.\n      Shahid\n(2012)\n',
 '\n      66.\n      Jigarthanda\n(2014)\n',
 '\n      67.\n      Gangs of Wasseypur\n(2012)\n',
 '\n      68.\n      Anand\n(1971)\n',
 '\n      69.\n      Paan Singh Tomar\n(2012)\n',
 '\n      70.\n      Sairat\n(2016)\n',
 '\n      71.\n      Bhaag Milkha Bhaag\n(2013)\n',
 '\n      72.\n      Maheshinte Prathikaaram\n(2016)\n',
 '\n      73.\n      Hera Pheri\n(2000)\n',
 '\n      74.\n      Sholay\n(1975)\n',
 '\n      75.\n      Swades: We, the People\n(2004)\n',
 '\n      76.\n      Theeran Adhigaaram Ondru\n(2017)\n',
 '\n      77.\n      Chak De! India\n(2007)\n',
 '\n      78.\n      Ustad Hotel\n(2012)\n',
 '\n      79.\n      Talvar\n(2015)\n',
 '\n      80.\n      Mughal-E-Azam\n(1960)\n',
 '\n      81.\n      Chhichhore\n(2019)\n',
 '\n      82.\n      Black\n(2005)\n',
 '\n      83.\n      Jo Jeeta Wohi Sikandar\n(1992)\n',
 '\n      84.\n      Zindagi Na Milegi Dobara\n(2011)\n',
 '\n      85.\n      Baasha\n(1995)\n',
 '\n      86.\n      Charulata\n(1964)\n',
 '\n      87.\n      Nil Battey Sannata\n(2015)\n',
 '\n      88.\n      Article 15\n(2019)\n',
 '\n      89.\n      Drishyam\n(2015)\n',
 '\n      90.\n      Virumandi\n(2004)\n',
 '\n      91.\n      Udaan\n(2010)\n',
 '\n      92.\n      A Wednesday\n(2008)\n',
 '\n      93.\n      Alai Payuthey\n(2000)\n',
 '\n      94.\n      Masaan\n(2015)\n',
 '\n      95.\n      Munna Bhai M.B.B.S.\n(2003)\n',
 '\n      96.\n      Sarfarosh\n(1999)\n',
 '\n      97.\n      Queen\n(2013)\n',
 '\n      98.\n      Roja\n(1992)\n',
 '\n      99.\n      Dil Chahta Hai\n(2001)\n',
 '\n      100.\n      OMG: Oh My God!\n(2012)\n',
 '\n      101.\n      Rang De Basanti\n(2006)\n',
 '\n      102.\n      Uri: The Surgical Strike\n(2019)\n',
 '\n      103.\n      Lagaan: Once Upon a Time in India\n(2001)\n',
 '\n      104.\n      Kahaani\n(2012)\n',
 '\n      105.\n      Andaz Apna Apna\n(1994)\n',
 '\n      106.\n      PK\n(2014)\n',
 '\n      107.\n      Lucia\n(2013)\n',
 '\n      108.\n      Bommarillu\n(2006)\n',
 '\n      109.\n      The Legend of Bhagat Singh\n(2002)\n',
 '\n      110.\n      Iqbal\n(2005)\n',
 '\n      111.\n      Barfi!\n(2012)\n',
 '\n      112.\n      Indian\n(1996)\n',
 '\n      113.\n      Section 375\n(2019)\n',
 '\n      114.\n      Bombay\n(1995)\n',
 '\n      115.\n      Maqbool\n(2003)\n',
 '\n      116.\n      Pink\n(2016)\n',
 '\n      117.\n      The Great Indian Kitchen\n(2021)\n',
 '\n      118.\n      Thadam\n(2019)\n',
 '\n      119.\n      Omkara\n(2006)\n',
 '\n      120.\n      Kshanam\n(2016)\n',
 '\n      121.\n      Pelli Choopulu\n(2016)\n',
 '\n      122.\n      Lage Raho Munna Bhai\n(2006)\n',
 '\n      123.\n      Shershaah\n(2021)\n',
 '\n      124.\n      Baahubali 2: The Conclusion\n(2017)\n',
 '\n      125.\n      Rangasthalam\n(2018)\n',
 '\n      126.\n      Pranchiyettan and the Saint\n(2010)\n',
 '\n      127.\n      Deewaar\n(1975)\n',
 '\n      128.\n      Naduvula Konjam Pakkatha Kaanom\n(2012)\n',
 '\n      129.\n      Athadu\n(2005)\n',
 '\n      130.\n      Evaru\n(2019)\n',
 '\n      131.\n      Padosan\n(1968)\n',
 '\n      132.\n      Gulaal\n(2009)\n',
 '\n      133.\n      Padayappa\n(1999)\n',
 '\n      134.\n      Thondimuthalum Dhriksakshiyum\n(2017)\n',
 '\n      135.\n      Haider\n(2014)\n',
 '\n      136.\n      Dilwale Dulhania Le Jayenge\n(1995)\n',
 '\n      137.\n      Take Off\n(2017)\n',
 '\n      138.\n      K.G.F: Chapter 1\n(2018)\n',
 '\n      139.\n      Maanagaram\n(2017)\n',
 '\n      140.\n      Aadukalam\n(2011)\n',
 '\n      141.\n      Vaaranam Aayiram\n(2008)\n',
 '\n      142.\n      Baishe Srabon\n(2011)\n',
 '\n      143.\n      Ugly\n(2013)\n',
 '\n      144.\n      Mother India\n(1957)\n',
 '\n      145.\n      Ulidavaru Kandanthe\n(2014)\n',
 '\n      146.\n      Special Chabbis\n(2013)\n',
 '\n      147.\n      Nayattu\n(2021)\n',
 '\n      148.\n      Ship of Theseus\n(2012)\n',
 '\n      149.\n      Badhaai ho\n(2018)\n',
 '\n      150.\n      Bajrangi Bhaijaan\n(2015)\n',
 '\n      151.\n      Dev.D\n(2009)\n',
 '\n      152.\n      Jalsaghar\n(1958)\n',
 '\n      153.\n      Deiva Thirumagal\n(2011)\n',
 '\n      154.\n      Karnan\n(2021)\n',
 '\n      155.\n      Vaastav: The Reality\n(1999)\n',
 '\n      156.\n      Kirik Party\n(2016)\n',
 '\n      157.\n      Vedam\n(2010)\n',
 '\n      158.\n      Mukkabaaz\n(2017)\n',
 '\n      159.\n      Gully Boy\n(2019)\n',
 '\n      160.\n      Ankhon Dekhi\n(2013)\n',
 '\n      161.\n      Company\n(2002)\n',
 '\n      162.\n      Manjhi: The Mountain Man\n(2015)\n',
 '\n      163.\n      Pizza\n(2012)\n',
 '\n      164.\n      Charlie\n(2015)\n',
 '\n      165.\n      Memories\n(2013)\n',
 '\n      166.\n      Arjun Reddy\n(2017)\n',
 '\n      167.\n      Poove Unakkaga\n(1996)\n',
 '\n      168.\n      Malik\n(2021)\n',
 '\n      169.\n      My Name Is Khan\n(2010)\n',
 '\n      170.\n      Ayyappanum Koshiyum\n(2020)\n',
 '\n      171.\n      Dil Bechara\n(2020)\n',
 '\n      172.\n      Kal Ho Naa Ho\n(2003)\n',
 '\n      173.\n      Jab We Met\n(2007)\n',
 '\n      174.\n      Border\n(1997)\n',
 '\n      175.\n      Vinnaithaandi Varuvaayaa\n(2010)\n',
 '\n      176.\n      Mumbai Police\n(2013)\n',
 '\n      177.\n      Kaakha..Kaakha: The Police\n(2003)\n',
 '\n      178.\n      Super 30\n(2019)\n',
 '\n      179.\n      Angamaly Diaries\n(2017)\n',
 '\n      180.\n      Thulladha Manamum Thullum\n(1999)\n',
 '\n      181.\n      Sonchiriya\n(2019)\n',
 '\n      182.\n      Unnaipol Oruvan\n(2009)\n',
 '\n      183.\n      Anjaam Pathiraa\n(2020)\n',
 '\n      184.\n      Hey Ram\n(2000)\n',
 '\n      185.\n      Lakshya\n(2004)\n',
 '\n      186.\n      Bãhubali: The Beginning\n(2015)\n',
 '\n      187.\n      Vettaiyaadu Vilaiyaadu\n(2006)\n',
 '\n      188.\n      Padman\n(2018)\n',
 '\n      189.\n      Dor\n(2006)\n',
 '\n      190.\n      Baby\n(2015)\n',
 '\n      191.\n      Airlift\n(2016)\n',
 '\n      192.\n      Hindi Medium\n(2017)\n',
 '\n      193.\n      Okkadu\n(2003)\n',
 '\n      194.\n      English Vinglish\n(2012)\n',
 '\n      195.\n      Gangaajal\n(2003)\n',
 '\n      196.\n      Manam\n(2014)\n',
 '\n      197.\n      The Lunchbox\n(2013)\n',
 '\n      198.\n      Johnny Gaddaar\n(2007)\n',
 '\n      199.\n      M.S. Dhoni: The Untold Story\n(2016)\n',
 '\n      200.\n      Ab Tak Chhappan\n(2004)\n',
 '\n      201.\n      Aayirathil Oruvan\n(2010)\n',
 '\n      202.\n      Pokiri\n(2006)\n',
 '\n      203.\n      Joji\n(2021)\n',
 '\n      204.\n      Goodachari\n(2018)\n',
 '\n      205.\n      Badla\n(2019)\n',
 '\n      206.\n      Secret Superstar\n(2017)\n',
 '\n      207.\n      Nayak: The Real Hero\n(2001)\n',
 '\n      208.\n      Stanley Ka Dabba\n(2011)\n',
 '\n      209.\n      Vicky Donor\n(2012)\n',
 '\n      210.\n      RangiTaranga\n(2015)\n',
 '\n      211.\n      Mr. India\n(1987)\n',
 '\n      212.\n      Raazi\n(2018)\n',
 '\n      213.\n      Mimi\n(2021)\n',
 '\n      214.\n      Don\n(1978)\n',
 '\n      215.\n      Velaiilla Pattadhari\n(2014)\n',
 '\n      216.\n      Udta Punjab\n(2016)\n',
 '\n      217.\n      Ko\n(2011)\n',
 '\n      218.\n      Thuppakki\n(2012)\n',
 '\n      219.\n      Aligarh\n(2015)\n',
 '\n      220.\n      Veer-Zaara\n(2004)\n',
 '\n      221.\n      Rock On!!\n(2008)\n',
 '\n      222.\n      Dasvidaniya\n(2008)\n',
 '\n      223.\n      Kaththi\n(2014)\n',
 '\n      224.\n      Arya\n(2004)\n',
 '\n      225.\n      Guru\n(2007)\n',
 '\n      226.\n      Kai po che!\n(2013)\n',
 '\n      227.\n      Samsara\n(2001)\n',
 '\n      228.\n      Ghilli\n(2004)\n',
 '\n      229.\n      24\n(2016)\n',
 '\n      230.\n      Oye Lucky! Lucky Oye!\n(2008)\n',
 '\n      231.\n      Rockstar\n(2011)\n',
 '\n      232.\n      Eega\n(2012)\n',
 '\n      233.\n      Avane Srimannarayana\n(2019)\n',
 '\n      234.\n      Mumbai Meri Jaan\n(2008)\n',
 '\n      235.\n      Kushi\n(2000)\n',
 '\n      236.\n      Ugramm\n(2014)\n',
 '\n      237.\n      Sir\n(2018)\n',
 '\n      238.\n      Kabhi Haan Kabhi Naa\n(1994)\n',
 '\n      239.\n      Darr\n(1993)\n',
 '\n      240.\n      The Tashkent Files\n(2019)\n',
 '\n      241.\n      Kapoor & Sons\n(2016)\n',
 '\n      242.\n      Newton\n(2017)\n',
 '\n      243.\n      C U Soon\n(2020)\n',
 '\n      244.\n      Aamir\n(2008)\n',
 '\n      245.\n      Earth\n(1998)\n',
 '\n      246.\n      Detective Byomkesh Bakshy!\n(2015)\n',
 '\n      247.\n      Madras Cafe\n(2013)\n',
 '\n      248.\n      Agneepath\n(1990)\n',
 '\n      249.\n      Sarkar\n(2005)\n',
 '\n      250.\n      Bheja Fry\n(2007)\n']

In [37]:
rating_india=[]
for i in soup_india.find_all('td',class_="ratingColumn imdbRating"):
    rating_india.append(i.text)
    
rating_india

['\n8.8\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.5\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.4\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.3\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.2\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.1\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n8.0\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.9\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.8\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.7\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n',
 '\n7.6\n']

In [38]:
release_year_india=[]
for i in soup_india.find_all('span',class_="secondaryInfo"):
    release_year_india.append(i.text)
    
release_year_india

['(2021)',
 '(1987)',
 '(2018)',
 '(2003)',
 '(2021)',
 '(2018)',
 '(1989)',
 '(1993)',
 '(1979)',
 '(1959)',
 '(2016)',
 '(1992)',
 '(2018)',
 '(2019)',
 '(2004)',
 '(1955)',
 '(2021)',
 '(2020)',
 '(2015)',
 '(2019)',
 '(2009)',
 '(2019)',
 '(2007)',
 '(2019)',
 '(2021)',
 '(1991)',
 '(2021)',
 '(1993)',
 '(2016)',
 '(2018)',
 '(2018)',
 '(1988)',
 '(1956)',
 '(1983)',
 '(1957)',
 '(2015)',
 '(1965)',
 '(2018)',
 '(1995)',
 '(1997)',
 '(2002)',
 '(2019)',
 '(1975)',
 '(2019)',
 '(2018)',
 '(2016)',
 '(2006)',
 '(2006)',
 '(2013)',
 '(2005)',
 '(2018)',
 '(2015)',
 '(2014)',
 '(1999)',
 '(2017)',
 '(2014)',
 '(2015)',
 '(1998)',
 '(1982)',
 '(2013)',
 '(2016)',
 '(2021)',
 '(2018)',
 '(2003)',
 '(2012)',
 '(2014)',
 '(2012)',
 '(1971)',
 '(2012)',
 '(2016)',
 '(2013)',
 '(2016)',
 '(2000)',
 '(1975)',
 '(2004)',
 '(2017)',
 '(2007)',
 '(2012)',
 '(2015)',
 '(1960)',
 '(2019)',
 '(2005)',
 '(1992)',
 '(2011)',
 '(1995)',
 '(1964)',
 '(2015)',
 '(2019)',
 '(2015)',
 '(2004)',
 '(2010)',
 '(2008)',
 '(2000)',
 '(2015)',
 '(2003)',
 '(1999)',
 '(2013)',
 '(1992)',
 '(2001)',
 '(2012)',
 '(2006)',
 '(2019)',
 '(2001)',
 '(2012)',
 '(1994)',
 '(2014)',
 '(2013)',
 '(2006)',
 '(2002)',
 '(2005)',
 '(2012)',
 '(1996)',
 '(2019)',
 '(1995)',
 '(2003)',
 '(2016)',
 '(2021)',
 '(2019)',
 '(2006)',
 '(2016)',
 '(2016)',
 '(2006)',
 '(2021)',
 '(2017)',
 '(2018)',
 '(2010)',
 '(1975)',
 '(2012)',
 '(2005)',
 '(2019)',
 '(1968)',
 '(2009)',
 '(1999)',
 '(2017)',
 '(2014)',
 '(1995)',
 '(2017)',
 '(2018)',
 '(2017)',
 '(2011)',
 '(2008)',
 '(2011)',
 '(2013)',
 '(1957)',
 '(2014)',
 '(2013)',
 '(2021)',
 '(2012)',
 '(2018)',
 '(2015)',
 '(2009)',
 '(1958)',
 '(2011)',
 '(2021)',
 '(1999)',
 '(2016)',
 '(2010)',
 '(2017)',
 '(2019)',
 '(2013)',
 '(2002)',
 '(2015)',
 '(2012)',
 '(2015)',
 '(2013)',
 '(2017)',
 '(1996)',
 '(2021)',
 '(2010)',
 '(2020)',
 '(2020)',
 '(2003)',
 '(2007)',
 '(1997)',
 '(2010)',
 '(2013)',
 '(2003)',
 '(2019)',
 '(2017)',
 '(1999)',
 '(2019)',
 '(2009)',
 '(2020)',
 '(2000)',
 '(2004)',
 '(2015)',
 '(2006)',
 '(2018)',
 '(2006)',
 '(2015)',
 '(2016)',
 '(2017)',
 '(2003)',
 '(2012)',
 '(2003)',
 '(2014)',
 '(2013)',
 '(2007)',
 '(2016)',
 '(2004)',
 '(2010)',
 '(2006)',
 '(2021)',
 '(2018)',
 '(2019)',
 '(2017)',
 '(2001)',
 '(2011)',
 '(2012)',
 '(2015)',
 '(1987)',
 '(2018)',
 '(2021)',
 '(1978)',
 '(2014)',
 '(2016)',
 '(2011)',
 '(2012)',
 '(2015)',
 '(2004)',
 '(2008)',
 '(2008)',
 '(2014)',
 '(2004)',
 '(2007)',
 '(2013)',
 '(2001)',
 '(2004)',
 '(2016)',
 '(2008)',
 '(2011)',
 '(2012)',
 '(2019)',
 '(2008)',
 '(2000)',
 '(2014)',
 '(2018)',
 '(1994)',
 '(1993)',
 '(2019)',
 '(2016)',
 '(2017)',
 '(2020)',
 '(2008)',
 '(1998)',
 '(2015)',
 '(2013)',
 '(1990)',
 '(2005)',
 '(2007)']

In [39]:
# Making dataframe 
import pandas as pd
df1_india=pd.DataFrame({'Movie_Name':name_india,'Released_year':release_year_india,'Rating':rating_india})
df_2=df1_india.iloc[:100]
df_2

                                       Movie_Name Released_year   Rating
0            \n      1.\n      Jai Bhim\n(2021)\n        (2021)  \n8.8\n
1             \n      2.\n      Nayakan\n(1987)\n        (1987)  \n8.5\n
2   \n      3.\n      Pariyerum Perumal\n(2018)\n        (2018)  \n8.5\n
3          \n      4.\n      Anbe Sivam\n(2003)\n        (2003)  \n8.5\n
4        \n      5.\n      Sardar Udham\n(2021)\n        (2021)  \n8.5\n
..                                            ...           ...      ...
95         \n      96.\n      Sarfarosh\n(1999)\n        (1999)  \n8.1\n
96             \n      97.\n      Queen\n(2013)\n        (2013)  \n8.1\n
97              \n      98.\n      Roja\n(1992)\n        (1992)  \n8.1\n
98    \n      99.\n      Dil Chahta Hai\n(2001)\n        (2001)  \n8.1\n
99  \n      100.\n      OMG: Oh My God!\n(2012)\n        (2012)  \n8.1\n

[100 rows x 3 columns]

## 4.Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
- a) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.
- b) Top 10 ODI Batsmen in men along with the records of their team and rating.
- c) Top 10 ODI bowlers along with the records of their team and rating.

In [40]:
page3=requests.get("https://www.icc-cricket.com/rankings/mens/team-rankings/odi")
#https://www.icc-cricket.com/rankings/mens/player-rankings/odi
page3

In [41]:
soup_icc=BeautifulSoup(page3.content)

In [74]:
team_name=[]
for i in soup_icc.find_all('span',class_="u-hide-phablet"):
    team_name.append(i.text)
t1=team_name[1:11]

#### Class name of Matches and Point is same so both data comes combine

In [76]:

'''matches=[]
for i in soup_icc.find_all('td',class_="rankings-block__banner--points"):
    matches.append(i.text)
matches'''

'matches=[]\nfor i in soup_icc.find_all(\'td\',class_="rankings-block__banner--points"):\n    matches.append(i.text)\nmatches'

In [68]:
matche_rating=[]
for i in soup_icc.find_all('td',class_="table-body__cell u-text-right rating"):
    matche_rating.append(i.text)
d1=matche_rating[0:10]

### Answer A

In [75]:
# Making dataframe 
import pandas as pd
df1_icc=pd.DataFrame({'Team':t1,'Rating':d1})
df1_icc

           Team Rating
0       England    119
1     Australia    116
2         India    113
3  South Africa     98
4      Pakistan     93
5    Bangladesh     91
6   West Indies     84
7     Sri Lanka     83
8   Afghanistan     62
9   Netherlands     48

In [77]:
page4=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi")
#https://www.icc-cricket.com/rankings/mens/player-rankings/odi
page4

In [78]:
soup_batsmen=BeautifulSoup(page4.content)

In [81]:
team=[]
for i in soup_batsmen.find_all('span',class_="table-body__logo-text"):
    team.append(i.text)
t1=team
matche_ratingg=[]
for i in soup_batsmen.find_all('td',class_="table-body__cell u-text-right rating"):
    matche_ratingg.append(i.text)
d1=matche_ratingg

### Answer B

In [83]:
# Making dataframe 
import pandas as pd
df1_icc_batsmen=pd.DataFrame({'Team':t1,'Rating':d1})
df1_icc_batsmen.iloc[0:10]

  Team Rating
0  IND    844
1  IND    813
2   NZ    801
3  AUS    779
4  ENG    775
5  AUS    762
6   WI    758
7   NZ    754
8   SA    747
9  AUS    709

### Answer C
- Top 10 ODI bowlers along with the records of their team and rating.

In [84]:
page5=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling")
page5

In [86]:
soup_bowler=BeautifulSoup(page5.content)

In [93]:
team=[]
for i in soup_bowler.find_all('span',class_="table-body__logo-text"):
    team.append(i.text)
t1=team
matche_ratingg=[]
for i in soup_bowler.find_all('td',class_="table-body__cell rating"):
    matche_ratingg.append(i.text)
d1=matche_ratingg

In [94]:
# Making dataframe 
import pandas as pd
df1_icc_bowler=pd.DataFrame({'Team':t1,'Rating':d1})
df1_icc_bowler[0:10]

  Team Rating
0  AUS    709
1  AFG    708
2  ENG    700
3  BAN    692
4   NZ    691
5  IND    679
6  AUS    652
7  BAN    650
8   SA    646
9  BAN    640